/**
 * counter-table.ts — GENERATED by `node scripts/gen-counter-table.mjs`. Do not edit by hand.
 *
 * The measured 9×9 payoff table FishAI v1.0 best-responds with. `p[i][j]` is the duplicate-
 * averaged score rate of `styles[i]` against `styles[j]` from the full-precision matrix-v2
 * artifact (36 cells × 4,300 pairs, health-gated); the diagonal is 0.5 by duplicate-pair
 * symmetry, unmeasured on purpose. `se[i][j]` is the paired standard error of that cell
 * (diagonal 0). Provenance is exported beside the numbers: an adaptive decision is only as
 * honest as the matrix it consults, so the artifact digest travels with the table and
 * `tests/bots/adaptive.test.ts` pins the two against each other.
 */
import type { StyleId } from '../roster.ts'

export interface CounterTable {
  readonly styles: readonly StyleId[]
  /** p[i][j] = score rate of styles[i] vs styles[j]; antisymmetric about 0.5; diagonal 0.5. */
  readonly p: readonly (readonly number[])[]
  /** Paired SE of each off-diagonal cell; diagonal 0. */
  readonly se: readonly (readonly number[])[]
  readonly provenance: {
    readonly artifact: string
    readonly recordsDigest: string
    readonly engineCommit: string
    readonly generatedAt: string
    readonly pairsPerCell: number
  }
}

export const COUNTER_TABLE: CounterTable = {
  styles: ['balanced', 'blitz', 'punter', 'banker', 'turtle', 'hoarder', 'scout', 'ghost', 'archivist'],
  p: [
    [0.5, 0.496163, 0.481047, 0.526977, 0.639651, 0.562442, 0.637791, 0.554884, 0.566047],
    [0.503837, 0.5, 0.480233, 0.521395, 0.642674, 0.568372, 0.635581, 0.562326, 0.56686],
    [0.518953, 0.519767, 0.5, 0.54686, 0.65814, 0.579535, 0.660349, 0.586744, 0.592558],
    [0.473023, 0.478605, 0.45314, 0.5, 0.617093, 0.528721, 0.605581, 0.530698, 0.541047],
    [0.360349, 0.357326, 0.34186, 0.382907, 0.5, 0.419767, 0.51593, 0.395698, 0.446047],
    [0.437558, 0.431628, 0.420465, 0.471279, 0.580233, 0.5, 0.581744, 0.478023, 0.507442],
    [0.362209, 0.364419, 0.339651, 0.394419, 0.48407, 0.418256, 0.5, 0.443372, 0.443837],
    [0.445116, 0.437674, 0.413256, 0.469302, 0.604302, 0.521977, 0.556628, 0.5, 0.494419],
    [0.433953, 0.43314, 0.407442, 0.458953, 0.553953, 0.492558, 0.556163, 0.505581, 0.5],
  ],
  se: [
    [0, 0.003928, 0.003608, 0.004723, 0.00456, 0.003707, 0.00469, 0.004991, 0.004644],
    [0.003928, 0, 0.004169, 0.004826, 0.004665, 0.004275, 0.004732, 0.004875, 0.004758],
    [0.003608, 0.004169, 0, 0.004771, 0.004631, 0.004198, 0.004618, 0.004885, 0.004687],
    [0.004723, 0.004826, 0.004771, 0, 0.004833, 0.004852, 0.004795, 0.00487, 0.004834],
    [0.00456, 0.004665, 0.004631, 0.004833, 0, 0.00474, 0.004965, 0.004931, 0.004859],
    [0.003707, 0.004275, 0.004198, 0.004852, 0.00474, 0, 0.004831, 0.004921, 0.004679],
    [0.00469, 0.004732, 0.004618, 0.004795, 0.004965, 0.004831, 0, 0.004988, 0.004562],
    [0.004991, 0.004875, 0.004885, 0.00487, 0.004931, 0.004921, 0.004988, 0, 0.00493],
    [0.004644, 0.004758, 0.004687, 0.004834, 0.004859, 0.004679, 0.004562, 0.00493, 0],
  ],
  provenance: {
    artifact: 'style-results.v2.json',
    recordsDigest: '0c3cb524a3534d4a',
    engineCommit: '1667a1d-dirty',
    generatedAt: '2026-08-22T21:49:51.484Z',
    pairsPerCell: 4300,
  },
}
