/**
 * counter-table.ts — GENERATED by `node scripts/gen-counter-table.mjs`. Do not edit by hand.
 *
 * The measured 9×9 payoff table FishAI v1.0 best-responds with. `p[i][j]` is the duplicate-
 * averaged score rate of `styles[i]` against `styles[j]` from the full-precision matrix-v2
 * artifact (36 cells × 4,300 pairs, health-gated); the diagonal is 0.5 by duplicate-pair
 * symmetry, unmeasured on purpose. `se[i][j]` is the paired standard error of that cell
 * (diagonal 0). Provenance is exported beside the numbers: an adaptive decision is only as
 * honest as the matrix it consults, so the artifact digest travels with the table and
 * `tests/bots/adaptive.test.ts` pins the two against each other.
 */
import type { StyleId } from '../roster.ts'

export interface CounterTable {
  readonly styles: readonly StyleId[]
  /** p[i][j] = score rate of styles[i] vs styles[j]; antisymmetric about 0.5; diagonal 0.5. */
  readonly p: readonly (readonly number[])[]
  /** Paired SE of each off-diagonal cell; diagonal 0. */
  readonly se: readonly (readonly number[])[]
  readonly provenance: {
    readonly artifact: string
    readonly recordsDigest: string
    readonly engineCommit: string
    readonly generatedAt: string
    readonly pairsPerCell: number
  }
}

export const COUNTER_TABLE: CounterTable = {
  styles: ['balanced', 'blitz', 'punter', 'banker', 'turtle', 'hoarder', 'scout', 'ghost', 'archivist'],
  p: [
    [0.5, 0.498488, 0.487326, 0.560116, 0.628837, 0.553372, 0.619651, 0.530116, 0.541395],
    [0.501512, 0.5, 0.489302, 0.562674, 0.635233, 0.556628, 0.625581, 0.533023, 0.543605],
    [0.512674, 0.510698, 0.5, 0.575698, 0.640581, 0.565349, 0.638256, 0.542907, 0.55593],
    [0.439884, 0.437326, 0.424302, 0.5, 0.585116, 0.497326, 0.559767, 0.509535, 0.482907],
    [0.371163, 0.364767, 0.359419, 0.414884, 0.5, 0.435349, 0.508605, 0.392093, 0.429419],
    [0.446628, 0.443372, 0.434651, 0.502674, 0.564651, 0.5, 0.575116, 0.468837, 0.489419],
    [0.380349, 0.374419, 0.361744, 0.440233, 0.491395, 0.424884, 0.5, 0.440581, 0.434302],
    [0.469884, 0.466977, 0.457093, 0.490465, 0.607907, 0.531163, 0.559419, 0.5, 0.492907],
    [0.458605, 0.456395, 0.44407, 0.517093, 0.570581, 0.510581, 0.565698, 0.507093, 0.5],
  ],
  se: [
    [0, 0.003848, 0.003202, 0.004793, 0.004719, 0.003768, 0.004827, 0.004979, 0.004696],
    [0.003848, 0, 0.004121, 0.004808, 0.00479, 0.004314, 0.004852, 0.00496, 0.004862],
    [0.003202, 0.004121, 0, 0.004795, 0.004751, 0.004119, 0.004843, 0.005023, 0.004782],
    [0.004793, 0.004808, 0.004795, 0, 0.005044, 0.004957, 0.004959, 0.005054, 0.004978],
    [0.004719, 0.00479, 0.004751, 0.005044, 0, 0.004733, 0.005038, 0.004964, 0.004966],
    [0.003768, 0.004314, 0.004119, 0.004957, 0.004733, 0, 0.004838, 0.004985, 0.004782],
    [0.004827, 0.004852, 0.004843, 0.004959, 0.005038, 0.004838, 0, 0.00491, 0.004627],
    [0.004979, 0.00496, 0.005023, 0.005054, 0.004964, 0.004985, 0.00491, 0, 0.004994],
    [0.004696, 0.004862, 0.004782, 0.004978, 0.004966, 0.004782, 0.004627, 0.004994, 0],
  ],
  provenance: {
    artifact: 'style-results.v2.json',
    recordsDigest: 'bcaab2bfb67f1139',
    engineCommit: 'ed188da-dirty',
    generatedAt: '2026-09-01T19:35:00.717Z',
    pairsPerCell: 4300,
  },
}
