/**
 * counter-table.ts — GENERATED by `node scripts/gen-counter-table.mjs`. Do not edit by hand.
 *
 * The measured 9×9 payoff table FishAI v1.0 best-responds with. `p[i][j]` is the duplicate-
 * averaged score rate of `styles[i]` against `styles[j]` from the full-precision matrix-v2
 * artifact (36 cells × 4,300 pairs, health-gated); the diagonal is 0.5 by duplicate-pair
 * symmetry, unmeasured on purpose. `se[i][j]` is the paired standard error of that cell
 * (diagonal 0). Provenance is exported beside the numbers: an adaptive decision is only as
 * honest as the matrix it consults, so the artifact digest travels with the table and
 * `tests/bots/adaptive.test.ts` pins the two against each other.
 */
import type { StyleId } from '../roster.ts'

export interface CounterTable {
  readonly styles: readonly StyleId[]
  /** p[i][j] = score rate of styles[i] vs styles[j]; antisymmetric about 0.5; diagonal 0.5. */
  readonly p: readonly (readonly number[])[]
  /** Paired SE of each off-diagonal cell; diagonal 0. */
  readonly se: readonly (readonly number[])[]
  readonly provenance: {
    readonly artifact: string
    readonly recordsDigest: string
    readonly engineCommit: string
    readonly generatedAt: string
    readonly pairsPerCell: number
  }
}

export const COUNTER_TABLE: CounterTable = {
  styles: ['balanced', 'blitz', 'punter', 'banker', 'turtle', 'hoarder', 'scout', 'ghost', 'archivist'],
  p: [
    [0.5, 0.49907, 0.488837, 0.559535, 0.625349, 0.554535, 0.621977, 0.531163, 0.544651],
    [0.50093, 0.5, 0.489767, 0.562326, 0.632326, 0.557558, 0.626628, 0.534302, 0.54593],
    [0.511163, 0.510233, 0.5, 0.574186, 0.637674, 0.566744, 0.641047, 0.546744, 0.559302],
    [0.440465, 0.437674, 0.425814, 0.5, 0.582558, 0.498721, 0.560465, 0.510581, 0.485814],
    [0.374651, 0.367674, 0.362326, 0.417442, 0.5, 0.437791, 0.511628, 0.393372, 0.431395],
    [0.445465, 0.442442, 0.433256, 0.501279, 0.562209, 0.5, 0.574767, 0.46907, 0.489302],
    [0.378023, 0.373372, 0.358953, 0.439535, 0.488372, 0.425233, 0.5, 0.440814, 0.433837],
    [0.468837, 0.465698, 0.453256, 0.489419, 0.606628, 0.53093, 0.559186, 0.5, 0.491512],
    [0.455349, 0.45407, 0.440698, 0.514186, 0.568605, 0.510698, 0.566163, 0.508488, 0.5],
  ],
  se: [
    [0, 0.003832, 0.003218, 0.004822, 0.004735, 0.003768, 0.004808, 0.004977, 0.004706],
    [0.003832, 0, 0.004105, 0.004844, 0.004799, 0.004304, 0.004841, 0.004968, 0.004852],
    [0.003218, 0.004105, 0, 0.004808, 0.004752, 0.004124, 0.004835, 0.005011, 0.00478],
    [0.004822, 0.004844, 0.004808, 0, 0.005043, 0.004943, 0.004965, 0.005049, 0.004986],
    [0.004735, 0.004799, 0.004752, 0.005043, 0, 0.00473, 0.005037, 0.00495, 0.004952],
    [0.003768, 0.004304, 0.004124, 0.004943, 0.00473, 0, 0.004833, 0.004988, 0.004772],
    [0.004808, 0.004841, 0.004835, 0.004965, 0.005037, 0.004833, 0, 0.004935, 0.004622],
    [0.004977, 0.004968, 0.005011, 0.005049, 0.00495, 0.004988, 0.004935, 0, 0.004977],
    [0.004706, 0.004852, 0.00478, 0.004986, 0.004952, 0.004772, 0.004622, 0.004977, 0],
  ],
  provenance: {
    artifact: 'style-results.v2.json',
    recordsDigest: '1d7d9f30b59c00f6',
    engineCommit: '1fdd22e',
    generatedAt: '2026-08-31T09:25:21.680Z',
    pairsPerCell: 4300,
  },
}
