/**
 * hodge.ts — the transitivity test: a combinatorial Hodge decomposition of the antisymmetric
 * payoff matrix into a **transitive** part and a **cyclic** part, plus the human-legible version
 * of the same fact, the enumeration of significant 3-cycles.
 *
 * BOT_LAB.md §1.2 and §4.4, after Balduzzi et al., *Re-evaluating Evaluation* (NeurIPS 2018):
 *
 * > Decompose the style payoff matrix into a transitive part and a cyclic part. If it is
 * > overwhelmingly transitive, publish a ranking and name a winner. If it has real cyclic
 * > energy, the answer is "no single best style exists".
 *
 * ## The decomposition, and why it is one line of algebra
 *
 * `A` is antisymmetric, so it is a *flow* on the complete graph over styles. The Hodge
 * decomposition of such a flow splits it orthogonally into a gradient flow and a divergence-free
 * residual:
 *
 * ```
 * A = grad(r) + C        grad(r)[i][j] = r[i] - r[j]        <grad(r), C> = 0
 * ```
 *
 * `grad(r)` is exactly the *transitive* part: a flow generated by a single rating vector, i.e.
 * one for which "i beats j by how much" is fully explained by a scalar per style. `C` is the
 * *cyclic* part: what no rating can explain. Because the two are orthogonal, the Frobenius norms
 * add, and `cyclicEnergy = ||C||^2 / ||A||^2` lands in `[0, 1]` with no normalisation choice to
 * argue about.
 *
 * On the complete graph with uniform weights the least-squares rating has a closed form. Minimise
 * `sum_ij (A_ij - r_i + r_j)^2`; the stationarity condition is `sum_j A_ij - n r_i + sum_j r_j = 0`,
 * and fixing the (arbitrary, orthogonal) constant by `sum_i r_i = 0` gives
 *
 * ```
 * r_i = (1 / n) * sum_j A_ij
 * ```
 *
 * — the row-mean of `A`, which for a payoff matrix is just "mean score, re-centred". That is the
 * whole computation. No solver, no tolerance, no iteration count that could be wrong.
 *
 * ## Hodge, and where Schur comes in
 *
 * BOT_LAB.md §4.4 names the split "Hodge/Schur". The **Hodge** half is the above and is what
 * `cyclicEnergy` measures. The **Schur** half is Balduzzi et al.'s *mElo* construction: the
 * cyclic residual `C` is a real antisymmetric matrix, so its real Schur form is block-diagonal
 * with `2x2` rotation blocks, and truncating to the leading `k` blocks gives the rank-`2k`
 * low-dimensional embedding mElo fits. That is a *representation* of the cyclic part, not a
 * different measurement of it — the energy it accounts for is the same `||C||^2` computed here.
 * This module reports the energy and the cycles; the embedding is a visualisation concern and is
 * deliberately not published as a separate finding.
 */
import type { StyleId } from '../../engine/index.ts'
import { frobeniusSq } from './linalg.ts'
import type { Matrix } from './linalg.ts'

export interface HodgeDecomposition {
  /** The least-squares rating, centred at 0. `transitive[i][j] = ratings[i] - ratings[j]`. */
  ratings: number[]
  transitive: Matrix
  cyclic: Matrix
  /** `||A||_F^2`. Zero only when every pairing is a dead heat. */
  totalEnergy: number
  transitiveEnergy: number
  /** `||C||_F^2 / ||A||_F^2` in `[0, 1]`. BOT_LAB.md §4.4 criterion 3 tests this < 0.15. */
  cyclicEnergy: number
  /** Orthogonality residual `|<T, C>| / ||A||^2` — asserted tiny; it is the proof the split is a split. */
  orthogonalityError: number
}

/** Combinatorial Hodge decomposition of an antisymmetric matrix. See the file header. */
export function hodgeDecompose(a: Matrix): HodgeDecomposition {
  const n = a.length
  const ratings = new Array<number>(n).fill(0)
  for (let i = 0; i < n; i++) {
    let s = 0
    for (let j = 0; j < n; j++) s += a[i][j]
    ratings[i] = n === 0 ? 0 : s / n
  }
  // Re-centre explicitly. With A exactly antisymmetric the row means already sum to 0, but the
  // gauge is the one free constant in the decomposition and pinning it is cheaper than trusting it.
  const shift = n === 0 ? 0 : ratings.reduce((s, v) => s + v, 0) / n
  for (let i = 0; i < n; i++) ratings[i] -= shift

  const transitive: Matrix = Array.from({ length: n }, (_, i) =>
    Array.from({ length: n }, (_, j) => ratings[i] - ratings[j]),
  )
  const cyclic: Matrix = Array.from({ length: n }, (_, i) =>
    Array.from({ length: n }, (_, j) => a[i][j] - transitive[i][j]),
  )

  const totalEnergy = frobeniusSq(a)
  const transitiveEnergy = frobeniusSq(transitive)
  const cyclicEnergyAbs = frobeniusSq(cyclic)
  let inner = 0
  for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) inner += transitive[i][j] * cyclic[i][j]

  return {
    ratings,
    transitive,
    cyclic,
    totalEnergy,
    transitiveEnergy,
    cyclicEnergy: totalEnergy === 0 ? 0 : cyclicEnergyAbs / totalEnergy,
    orthogonalityError: totalEnergy === 0 ? 0 : Math.abs(inner) / totalEnergy,
  }
}

/** One directed 3-cycle `styles[0] > styles[1] > styles[2] > styles[0]`. */
export interface Cycle3 {
  styles: [StyleId, StyleId, StyleId]
  /** The three winning score rates, in the cycle's order. */
  edges: [number, number, number]
  /** `min` of the three — how weak the weakest link of the cycle is. BOT_LAB.md §7.1's field. */
  minEdge: number
  /** The largest BH q-value among the three edges. */
  maxQ: number
  /** True iff all three edges survived BH at the run's alpha. */
  significant: boolean
}

/**
 * Enumerate directed 3-cycles.
 *
 * A cycle needs each of its three edges to be a *win*, and — for BOT_LAB.md §4.4's "3-cycle
 * count: triples with A>B>C>A **at significance**" — each edge to have survived the
 * Benjamini-Hochberg correction of [stats.ts](stats.ts). That correction is not decoration here:
 * with 36 cells at alpha 0.05 about 1.8 edges are spurious, and two spurious edges are exactly
 * how a spurious 3-cycle appears in an otherwise transitive population.
 *
 * Each unordered triple is examined in both orientations, but at most one of them can be a cycle
 * (reversing every edge of a cycle gives the other orientation, which requires every edge to lose)
 * so no triple is ever double-reported.
 *
 * @param sig `sig[i][j]` — is "i beats j" significant after BH? Symmetric.
 * @param q   `q[i][j]` — the BH q-value of the pairing. Symmetric.
 */
export function findCycles(
  styles: readonly StyleId[],
  p: Matrix,
  sig: boolean[][],
  q: Matrix,
): Cycle3[] {
  const n = styles.length
  const out: Cycle3[] = []
  const beats = (i: number, j: number): boolean => p[i][j] > 0.5

  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) {
      for (let k = j + 1; k < n; k++) {
        const orientations: [number, number, number][] = [
          [i, j, k],
          [i, k, j],
        ]
        for (const [x, y, z] of orientations) {
          if (!(beats(x, y) && beats(y, z) && beats(z, x))) continue
          const edges: [number, number, number] = [p[x][y], p[y][z], p[z][x]]
          const qs = [q[x][y], q[y][z], q[z][x]]
          out.push({
            styles: [styles[x], styles[y], styles[z]],
            edges,
            minEdge: Math.min(...edges),
            maxQ: Math.max(...qs),
            significant: sig[x][y] && sig[y][z] && sig[z][x],
          })
        }
      }
    }
  }
  // Strongest cycles first: a cycle whose weakest edge is furthest from a coin flip is the one
  // worth drawing on the counter-graph.
  out.sort((a, b) => b.minEdge - a.minEdge || a.styles.join().localeCompare(b.styles.join()))
  return out
}
