/**
 * engine-copy.test.ts — the room's rules engine is the site's rules engine.
 *
 * The shared room's authority is a Supabase Edge Function, which is deployed by uploading a flat
 * list of files. It cannot import `lib/engine/` — nothing in the deployed bundle can see this
 * repository — so `supabase/functions/room/engine/` holds a generated copy of the nine non-bot
 * modules that `newGame`, `reduce`, `publicView` and `seatView` transitively need.
 *
 * A copy of a rules engine that has quietly drifted from the original is the worst failure this
 * feature has available to it. It does not crash and it does not look wrong: the server enforces
 * one rule set, every client explains a different one, and the disagreement reaches a player as an
 * unreproducible "it rejected a legal move". So the copy is generated by
 * `scripts/sync-room-engine.mjs` and pinned here.
 *
 * The two trees are read through Vite's `?raw`, via `import.meta.glob`, rather than through
 * `node:fs`. This project has no `@types/node` — the lab reads its committed artifact the same
 * way — and a glob has the property a hand-written list of nine imports would not: a tenth module
 * appearing in either tree shows up here on its own, instead of being silently unchecked.
 *
 * These assertions are deliberately an INDEPENDENT check rather than a call into the sync
 * script's own helpers. A test that shares the generator's description of a correct copy agrees
 * with the generator by construction, including when the generator is wrong. Comparing bytes
 * cannot do that.
 */
import { describe, expect, it } from 'vitest'

const ORIGINALS = import.meta.glob('../../lib/engine/*.ts', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>

const COPIES = import.meta.glob('../../supabase/functions/room/engine/*.ts', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>

/** The sync script's header, which is the only thing a copy may add to its original. */
const BANNER =
  /^\/\/ GENERATED FILE — DO NOT EDIT\.\n\/\/ Copied verbatim from lib\/engine\/(\S+) by scripts\/sync-room-engine\.mjs\.\n\/\/ [^\n]*\n\n/

const basename = (path: string): string => path.slice(path.lastIndexOf('/') + 1)

const copies = Object.entries(COPIES)
  .map(([path, source]) => ({ name: basename(path), source }))
  .sort((a, b) => a.name.localeCompare(b.name))

const originalsByName = new Map(Object.entries(ORIGINALS).map(([path, source]) => [basename(path), source]))

/** Every `from './x.ts'` in a module — what a flat copy has to be closed under. */
function relativeImports(source: string): string[] {
  return [...source.matchAll(/from\s+'\.\/([^']+)'/g)].map((m) => m[1])
}

describe('the room Edge Function bundles the real rules engine', () => {
  it('copies something at all, and only .ts modules', () => {
    expect(copies.length).toBeGreaterThan(0)
    expect(copies.every((c) => c.name.endsWith('.ts'))).toBe(true)
  })

  // The assertion the whole feature rests on. Byte-for-byte after the generated header — not
  // "compiles the same", not "exports the same names".
  for (const { name, source } of copies) {
    it(`${name} is byte-identical to lib/engine/${name}`, () => {
      const match = BANNER.exec(source)
      expect(match, `${name} is missing the generated header — was it hand-edited?`).not.toBeNull()
      expect(match?.[1], `${name}'s header names the wrong source module`).toBe(name)

      const origin = originalsByName.get(name)
      expect(origin, `${name} has no original in lib/engine/`).toBeDefined()

      expect(
        source.slice(match?.[0].length ?? 0),
        `supabase/functions/room/engine/${name} has drifted from lib/engine/${name}. ` +
          'Run: node scripts/sync-room-engine.mjs',
      ).toBe(origin)
    })
  }

  /**
   * The property that makes a FLAT copy legal in the first place: every module's imports are
   * `./sibling.ts` and every one of those siblings was copied too. If someone adds an import of a
   * tenth module to any of the nine, this fails here rather than at cold start in production with
   * a module-not-found the browser sees as a 500.
   */
  it('is closed under import — no module reaches outside the copied set', () => {
    const present = new Set(copies.map((c) => c.name))
    const missing: string[] = []

    for (const { name, source } of copies) {
      for (const dep of relativeImports(source)) {
        if (!present.has(dep)) missing.push(`${name} -> ./${dep}`)
      }
      // A parent-relative import would resolve in `lib/engine/` and be missing in the bundle.
      expect(source, `${name} imports out of the bundle with '../'`).not.toMatch(/from\s+'\.\.\//)
    }

    expect(missing, 'imports with no file in the bundle').toEqual([])
  })

  /**
   * The bots are the larger half of the engine and exactly the half a room has no use for — the
   * owner asked for six humans and no bots. Bundling `lib/engine/index.ts` would have dragged the
   * whole roster in; this proves the closure stayed narrow.
   */
  it('leaves the bots, and the barrel that would pull them in, out of the bundle', () => {
    expect(copies.map((c) => c.name)).not.toContain('index.ts')
    for (const { source } of copies) expect(source).not.toMatch(/from\s+'\.\/bots/)
  })

  it('carries the four entry points the function actually calls', () => {
    const find = (name: string): string => copies.find((c) => c.name === name)?.source ?? ''
    expect(find('reduce.ts')).toMatch(/export function newGame\b/)
    expect(find('reduce.ts')).toMatch(/export function reduce\b/)
    expect(find('views.ts')).toMatch(/export function publicView\b/)
    expect(find('views.ts')).toMatch(/export function seatView\b/)
  })
})
